### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pjebs** [crewdevio/Snel#1]
What exactly does this project do compared to the normal use of svelte compiler? What are its advantages?

**Comment by buttercubz** [comment]
> What exactly does this project do compared to the normal use of svelte compiler? What are its advantages?

snel is a set of tools that a set allows compiling svelte projects to javascript using deno as runtime, behind snel uses the official svelte compiler but already compiled and adapted so that it can work in deno. the main idea is that you can create svelte projects using deno as a runtime without adding too many configurations and also have support for css preprocessors and typescript  without the need to add plugins or extra configurations

**Comment by pjebs** [comment]
1. So currently it just replaces node/npm for building purposes. (with some slight adjustments in importing packages)
2. In the future, it will also provide a backend using Deno with SSR functionality?

**Comment by buttercubz** [comment]
> 1. So currently it just replaces node/npm for building purposes. (with some slight adjustments in importing packages)
> 2. In the future, it will also provide a backend using Deno with SSR functionality?

yes, future plans are to provide SSR using deno as backend runtime

**Comment by pjebs** [comment]
thanks
